# Case NPS Preditivo - Limpeza e Tratamentos dos Dados

## Pacotes

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

## Leitura de Dados

In [ ]:
#load dos dados
dados = pd.read_csv("https://raw.githubusercontent.com/braga0m/TechChallenge1/refs/heads/main/dados/desafio_nps_fase_1.csv")

In [ ]:
#20 primeiras linhas dos dados
dados.head(10)

In [ ]:
#informações básica dos dados
dados.info()

In [ ]:
#tamanho dos dados
dados.shape

In [ ]:
#summary dos dados
dados.describe().round(3)

In [ ]:
#checagem de duplicadas nos identificadores
a = len(dados["customer_id"].unique())
b = len(dados["order_id"].unique())

#
print(a,b)

2500 2500

In [ ]:

dados.drop_duplicates()

,customer_id,customer_age,customer_region,customer_tenure_months,order_id,order_value,items_quantity,discount_value,payment_installments,delivery_time_days,...,freight_value,delivery_attempts,customer_service_contacts,resolution_time_days,nps_score,repeat_purchase_30d,complaints_count,csat_internal_score,complaints,nps_classe
0,1,63,Nordeste,14,50001,139.73,4,39.35,4,2,...,55.53,3,0,4,6.9,0,3,6.5,1,Detratores
1,2,20,Sul,1,50002,458.95,2,9.51,10,6,...,28.23,3,0,10,2.4,0,3,0.0,1,Detratores
2,3,46,Nordeste,111,50003,507.06,5,42.82,6,6,...,40.99,1,4,5,4.8,0,7,1.5,1,Detratores
3,4,52,Centro-Oeste,117,50004,302.19,2,19.58,9,5,...,35.24,3,1,11,5.9,0,4,0.3,1,Detratores
4,5,56,Norte,50,50005,253.06,1,29.37,11,13,...,39.32,1,1,0,6.1,0,3,7.9,1,Detratores
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,2496,51,Sul,96,52496,615.81,6,11.41,2,14,...,28.96,2,1,2,3.7,0,3,4.3,1,Detratores
2496,2497,37,Sul,89,52497,73.03,1,36.44,3,12,...,27.42,2,2,7,3.7,0,4,2.5,1,Detratores
2497,2498,19,Sudeste,98,52498,522.78,1,4.84,9,2,...,38.94,1,1,1,7.4,0,3,6.2,1,Neutros
2498,2499,41,Sul,51,52499,55.87,2,2.11,2,14,...,29.10,3,3,0,2.3,0,5,1.7,1,Detratores
2499,2500,35,Nordeste,109,52500,420.94,1,16.51,4,11,...,34.16,3,1,0,10.0,1,2,7.6,1,Promotores

## Criação de novas colunas

In [ ]:
#criando as categorias a partir do nps_score
# aparentemente np.select() é mais eficiente
dados["nps_categoria"] = dados["nps_score"].case_when([
    (dados["nps_score"] >= 9, "Promotores"),
    ((dados["nps_score"] >= 7) & (dados["nps_score"] < 9), "Neutros"),
    ((dados["nps_score"] >= 0) & (dados["nps_score"] < 7), "Detratores")
    ])


dados[["nps_score", "nps_categoria", "csat_internal_score"]].head(20)

In [ ]:
#variável categórica se teve uma ou mais reclamação ou não
dados["complaints"] = np.where(dados["complaints_count"] > 0, 1, 0)

dados[["complaints", "complaints_count"]].head(20)

## Renomeando as colunas

In [ ]:
#renomeando as colunas
dados2 = dados.rename(columns = {
"customer_id": "Cliente ID",
"order_id": "Pedido ID",
"customer_age": "Idade do cliente",
"customer_region": "Região do Cliente",
"customer_tenure_months": "Tempo de relacionamento com o cliente",
"order_value": "Valor do pedido",
"items_quantity": "Quantidade de itens",
"discount_value": "Valor do desconto",
"payment_installments": "Número de parcelas",
"delivery_time_days": "Tempo total da entrega",
"delivery_delay_days": "Tempo de atraso da entrega",
"freight_value": "Valor do frete",
"delivery_attempts": "Número de tentativas de entrega",
"customer_service_contacts": "Número atendimentos",
"resolution_time_days": "Tempo de resolucão de problemas",
"complaints_count": "Número de reclamações",
"repeat_purchase_30d": "Recompra em 30 dias",
"complaints": "Reclamação",
"nps_score": "NPS escore",
"csat_internal_score": "CSAT escore"
})

In [ ]:
dados2.head(20)

,Cliente ID,Idade do cliente,Região do Cliente,Tempo de relacionamento com o cliente,Pedido ID,Valor do pedido,Quantidade de itens,Valor do desconto,Número de parcelas,Tempo total da entrega,...,Valor do frete,Número de tentativas de entrega,Número atendimentos,Tempo de resolucão de problemas,NPS escore,Recompra em 30 dias,Número de reclamações,CSAT escore,Reclamação,nps_classe
0,1,63,Nordeste,14,50001,139.73,4,39.35,4,2,...,55.53,3,0,4,6.9,0,3,6.5,1,Detratores
1,2,20,Sul,1,50002,458.95,2,9.51,10,6,...,28.23,3,0,10,2.4,0,3,0.0,1,Detratores
2,3,46,Nordeste,111,50003,507.06,5,42.82,6,6,...,40.99,1,4,5,4.8,0,7,1.5,1,Detratores
3,4,52,Centro-Oeste,117,50004,302.19,2,19.58,9,5,...,35.24,3,1,11,5.9,0,4,0.3,1,Detratores
4,5,56,Norte,50,50005,253.06,1,29.37,11,13,...,39.32,1,1,0,6.1,0,3,7.9,1,Detratores
5,6,35,Sudeste,75,50006,568.76,6,36.58,3,4,...,41.82,2,2,3,0.9,0,5,1.5,1,Detratores
6,7,37,Sudeste,68,50007,41.29,3,99.62,6,8,...,35.83,3,3,4,1.4,0,6,0.6,1,Detratores
7,8,60,Sul,37,50008,428.76,4,29.54,10,11,...,44.50,1,0,2,0.0,0,2,4.1,1,Detratores
8,9,40,Sul,60,50009,121.56,3,91.95,6,6,...,24.88,2,1,9,6.2,0,3,0.8,1,Detratores
9,10,51,Sudeste,70,50010,411.01,6,37.47,3,9,...,30.59,1,0,7,2.7,0,2,4.2,1,Detratores
10,11,50,Centro-Oeste,28,50011,616.17,2,23.00,8,4,...,52.94,3,0,7,5.3,0,6,2.7,1,Detratores
11,12,67,Norte,81,50012,509.48,2,10.42,1,11,...,46.92,2,1,3,7.0,0,2,5.8,1,Neutros
12,13,65,Centro-Oeste,85,50013,588.28,6,12.54,5,11,...,28.67,2,1,9,3.7,0,4,0.4,1,Detratores
13,14,27,Sudeste,42,50014,165.19,5,52.82,5,10,...,63.92,3,0,8,2.9,0,2,3.5,1,Detratores
14,15,50,Sudeste,113,50015,220.81,3,30.73,6,7,...,45.96,1,1,4,2.7,0,3,2.4,1,Detratores
15,16,64,Norte,114,50016,732.83,2,13.24,8,9,...,46.78,2,1,8,6.0,0,2,0.0,1,Detratores
16,17,50,Norte,70,50017,391.66,4,0.25,11,3,...,59.78,2,1,6,1.9,0,4,2.7,1,Detratores
17,18,65,Sul,21,50018,483.04,1,28.08,1,12,...,44.76,2,1,10,4.8,0,4,0.0,1,Detratores
18,19,43,Sul,86,50019,383.98,3,33.61,11,3,...,25.24,2,2,3,3.4,0,4,2.0,1,Detratores
19,20,37,Centro-Oeste,74,50020,288.93,2,20.80,9,9,...,62.02,1,1,3,2.0,0,4,5.0,1,Detratores

## Exportação

In [ ]:
#exportação das bases de dados
dados.to_csv('dados_ecommerce.csv', index=False)
dados2.to_csv('dados_ecommerce_renomeado.csv', index=False)